### ISSUE TITLE
lack of the "/SGR/data/act_prediction_result/train.json" file

### ISSUE THREAD

**Issue by Lavau** [yieshah/SGR#1]
When I run the code, this error encountered. I went through all the folders and didn't find it.
Could you please add this file? Thank you!!!

Traceback (most recent call last):
  File "/home/wuchenyu/SGR/main.py", line 78, in <module>
    train_data = MmdialData(args, mode = 'train')
  File "/home/wuchenyu/SGR/MmdialDataPre.py", line 105, in __init__
    with open(act_prediction_path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/wuchenyu/SGR/data/act_prediction_result/train.json'

**Comment by YuxiaWu** [comment]
@Lavau Hi, thanks for your interest. You can download the checkpoint of action prediction. The `train.json` can be obtained by `python get_action_predction_results.py`.

**Comment by Lavau** [comment]
Thank you for your reply!!!
OK, When I run `python get_action_predction_results.py`, this error encountered

<_io.TextIOWrapper name='./DialoGPT-small/vocab.json' mode='r' encoding='utf-8'>
Traceback (most recent call last):
  File "/home/wuchenyu/SGR/get_action_prediction_result.py", line 48, in <module>
    train = TextDataset.create_data(f'/home/wuchenyu/SGR/dialogpt/resources/train.{input_format}', tokenizer_or_transformer_model=transformer_model, end_token=' <|endofaction|>', remove_tokens={}, split_token='<|endofbelief|>', split=(1,), shuffle=False)
  File "/home/wuchenyu/SGR/dialogpt/dataloader.py", line 111, in create_data
    splits.append(cls(data[begin_idx: end_idx], training=training[i], **kwargs))
  File "/home/wuchenyu/SGR/dialogpt/dataloader.py", line 132, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_or_transformer_model)
  File "/home/wuchenyu/anaconda3/envs/mm/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 899, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/wuchenyu/anaconda3/envs/mm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2110, in from_pretrained
    return cls._from_pretrained(
  File "/home/wuchenyu/anaconda3/envs/mm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2148, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
  File "/home/wuchenyu/anaconda3/envs/mm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2336, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/wuchenyu/anaconda3/envs/mm/lib/python3.10/site-packages/transformers/models/gpt2/tokenization_gpt2.py", line 157, in __init__
    self.encoder = json.load(vocab_handle)
  File "/home/wuchenyu/anaconda3/envs/mm/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/wuchenyu/anaconda3/envs/mm/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/wuchenyu/anaconda3/envs/mm/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/wuchenyu/anaconda3/envs/mm/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I read this  file "./DialoGPT-small/vocab.json" and fonud that it is a HTML file and isn't a json file.

🤧🤧🤧

**Comment by YuxiaWu** [comment]
@Lavau Hi, sorry for that. You can download the files at https://huggingface.co/microsoft/DialoGPT-small/tree/main

**Comment by Lavau** [comment]
Thank you for your reply!!  
美丽的姐姐🌹🌹🌹
When I run ` python get_action_predction_results.py`, I found that this method `create_data()` isn't overwritten in 
class `TextDataset` and  uses the superclass `BaseDataset` definition for it. But the actual parameter call is different from the definition. 
```python
train = TextDataset.create_data(f'./dialogpt/resources/train.{input_format}', 
                                tokenizer_or_transformer_model=transformer_model, 
                                end_token=' <|endofaction|>', remove_tokens={}, 
                                split_token='<|endofbelief|>', split=(1,), shuffle=False)
```
<img width="698" alt="image" src="https://github.com/YuxiaWu/SGR/assets/46114201/301a967d-2984-4c2a-baa7-3a9f9d920268">

```python
def create_data(cls, paths, split=(1,), training=(True,), shuffle=True, **kwargs):
```
<img width="682" alt="image" src="https://github.com/YuxiaWu/SGR/assets/46114201/39c2e5b7-1d1a-4027-833b-6344d83e8d66">

**Comment by Lavau** [comment]
> @Lavau Hi, sorry for that. You can download the files at https://huggingface.co/microsoft/DialoGPT-small/tree/main

need to download the four files, as shown the png. And put them to the folder `DialogGPT-small`
<img width="590" alt="image" src="https://github.com/YuxiaWu/SGR/assets/46114201/7f1e0505-e527-43e3-8a6a-ba01a8eac5b6">

**Comment by Lavau** [comment]
@YuxiaWu Thanks for your reply...🌹🌹🌹
Run `python get_action_predction_result.py`, and the error appeared.
So, I have a question: Where can I download this checkpoint file `action_prediction_woimage_microsoft#DialoGPT-small_03-08-2021 01:57:20.1627927040_val_acc-AR:0.353_val_loss-L:6.16 LR:6.157.th`?
<img width="1077" alt="image" src="https://github.com/YuxiaWu/SGR/assets/46114201/e202bd62-65c2-49f0-808d-233739d1ba44">

**Comment by Lavau** [comment]
@YuxiaWu Thanks for your reply...🌹🌹🌹
Run python get_action_predction_result.py, and the error appeared.
So, I have a question: Where can I download this checkpoint file `action_prediction_woimage_microsoft#DialoGPT-small_03-08-2021 01:57:20.1627927040_val_acc-AR:0.353_val_loss-L:6.16 LR:6.157.th`? 
The checkpint file in readme.me isn't this file.🤧🤧
Thanks

<img width="1084" alt="image" src="https://github.com/YuxiaWu/SGR/assets/46114201/e61970c2-028f-4a54-bc3c-bc3f409e7ad4">

**Comment by YuxiaWu** [comment]
@Lavau Sorry for responding late. This checkpoint is trained without images. I forget to copy it to my local machine. You can train the action prediction if you need the "woimage" version.

**Comment by Lavau** [comment]
@YuxiaWu 
Thanks for your reply...🌹🌹🌹
I will do it if I actually need this checkpoint. Thank you ....
🌹🌹🌹美丽的漂亮姐姐🌹🌹🌹

**Comment by Lavau** [comment]
> @YuxiaWu Thanks for your reply...🌹🌹🌹 Run python get_action_predction_result.py, and the error appeared. So, I have a question: Where can I download this checkpoint file `action_prediction_woimage_microsoft#DialoGPT-small_03-08-2021 01:57:20.1627927040_val_acc-AR:0.353_val_loss-L:6.16 LR:6.157.th`? The checkpint file in readme.me isn't this file.🤧🤧 Thanks
> 
> <img alt="image" width="1084" src="https://private-user-images.githubusercontent.com/46114201/347415939-e61970c2-028f-4a54-bc3c-bc3f409e7ad4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzA2NDEsIm5iZiI6MTcyMjE3MDM0MSwicGF0aCI6Ii80NjExNDIwMS8zNDc0MTU5MzktZTYxOTcwYzItMDI4Zi00YTU0LWJjM2MtYmMzZjQwOWU3YWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDEyMzkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiN2IxNjk1NzBjZjE3ZTU2YzEwZTVmMDQwYWE2NGQ5OGM5MzNjYzFlMTY2NTlhYWNjNTVjNmYzNmQzYjNiZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f0RZU9nPqUzT1D3NP53fyrhXPnzZaaMqyU1hO4o-b9I">

@YuxiaWu
您好！
我再次详细看了`get_action_prediction_result.py`文件里面的代码，简单修改了一些地方，用了您公布的checkpoint，在`data`里面得到到了预测的`act_prediction_result`文件夹及其文件。之后，我尝试运行`CUDA_VISIBLE_DEVICES=1 python main.py --with_image --lr 0.001 `，开始训练。
然而，出现了新问题：
<img width="778" alt="image" src="https://github.com/user-attachments/assets/0cd00592-8228-4cde-a11e-0d644ebb888d">
按照类`SignedGraphConvolutionalNetwork`的定义与方法`setup_layers`的内容，`self.node_count`似乎应该是一个`tensor`。实际上，`self.node_count`却是一个`int`值。
<img width="825" alt="image" src="https://github.com/user-attachments/assets/6e274173-a0c1-4e92-a9e9-8ce3b41737a6">
请问，我应该怎么纠正它呢？谢谢啦，期待您的回复！！！

**Comment by YuxiaWu** [comment]
@Lavau You can try torch.Tensor to map it into a tensor

**Comment by licpp** [comment]
@Lavau I am replicating this project now, Is your problem solvedd?

**Comment by Lavau** [comment]
抱歉，这个还没有解决。self.node_count是一个int值，就算改为tensor的格式，也是一维的。然后对于它的shape要求，却（至少）是两维的。（self.X就是self.node_count）







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuxiaWu/SGR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月7日(星期三) 上午9:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuxiaWu/SGR] lack of the "/SGR/data/act_prediction_result/train.json" file (Issue #1)





 
@Lavau I am replicating this project now, Is your problem solvedd?

**Comment by YuxiaWu** [comment]
@Lavau Have you solved the problem? I will check it again in the following days.

**Comment by Lavau** [comment]
@YuxiaWu
Thanks!  Solved the problem!
